
import { UserRole, RoleDetails } from './types';
import { LandOwnerIcon, PublicUserIcon, AgriConsultantIcon, SupplierIcon, BuyerIcon, SellerIcon, TransportProviderIcon, BankFinancialIcon, DataAnalystIcon } from './components/icons/RoleIcons';

export const ROLE_DETAILS: Record<UserRole, RoleDetails> = {
  [UserRole.LandOwner]: {
    role: UserRole.LandOwner,
    title: 'Land Owner',
    description: 'Manage land, crops, and connect with the marketplace.',
    icon: LandOwnerIcon,
    coreObjective: 'To optimize land usage, monitor crop cycles, and manage farm resources efficiently.',
    dashboardElements: ['Interactive Land Map', 'Crop Cycle Calendar', 'Inventory Management', 'Marketplace Listings'],
    uniqueInteractions: ['Creating and updating land plot details', 'Scheduling crop activities', 'Connecting directly with suppliers and buyers for their produce.'],
  },
  [UserRole.PublicUser]: {
    role: UserRole.PublicUser,
    title: 'Public User',
    description: 'Access market prices, news, and public information.',
    icon: PublicUserIcon,
    coreObjective: 'To stay informed about agricultural market trends, news, and public data.',
    dashboardElements: ['Live Market Prices', 'Agricultural News Feed', 'Public Product Listings', 'Weather Forecasts'],
    uniqueInteractions: ['Viewing public data without modification rights', 'Setting up alerts for market price changes.'],
  },
  [UserRole.AgriConsultant]: {
    role: UserRole.AgriConsultant,
    title: 'Agri Consultant',
    description: 'Provide expert services and manage client portfolios.',
    icon: AgriConsultantIcon,
    coreObjective: 'To provide specialized advice and services (e.g., soil testing, crop planning) to clients.',
    dashboardElements: ['Client Portfolio Management', 'Service Booking Calendar', 'Market Analysis Tools', 'Knowledge Base'],
    uniqueInteractions: ['Acting as an intermediary for farmers/land owners', 'Publishing advisory articles and reports.'],
  },
  [UserRole.Supplier]: {
    role: UserRole.Supplier,
    title: 'Supplier',
    description: 'List products like seeds, fertilizers, and equipment.',
    icon: SupplierIcon,
    coreObjective: 'To sell agricultural inputs (seeds, fertilizers, etc.) to farmers and businesses.',
    dashboardElements: ['Product Catalog Management', 'Inventory Tracking', 'Order Fulfillment Queue', 'Sales Analytics'],
    uniqueInteractions: ['Managing a B2B product catalog', 'Processing bulk orders', 'Setting tiered pricing for different buyers.'],
  },
  [UserRole.Buyer]: {
    role: UserRole.Buyer,
    title: 'Buyer',
    description: 'Search for produce, place orders, and track deliveries.',
    icon: BuyerIcon,
    coreObjective: 'To find and purchase agricultural produce or products efficiently.',
    dashboardElements: ['Advanced Product Search', 'Order Tracking', 'Supplier Ratings & Reviews', 'Manage Purchase Orders'],
    uniqueInteractions: ['Placing purchase orders', 'Negotiating prices with sellers', 'Tracking shipments from multiple sellers.'],
  },
  [UserRole.Seller]: {
    role: UserRole.Seller,
    title: 'Seller',
    description: 'List produce, manage sales, and communicate with buyers.',
    icon: SellerIcon,
    coreObjective: 'To sell agricultural produce to a wide market of buyers.',
    dashboardElements: ['My Produce Listings', 'Sales Performance Dashboard', 'Buyer Messaging Center', 'Inventory Management'],
    uniqueInteractions: ['Listing perishable goods with expiry dates', 'Responding to buyer inquiries and offers.'],
  },
  [UserRole.TransportProvider]: {
    role: UserRole.TransportProvider,
    title: 'Transport Provider',
    description: 'Offer logistics services and manage shipments.',
    icon: TransportProviderIcon,
    coreObjective: 'To provide reliable transportation and logistics services for agricultural goods.',
    dashboardElements: ['Shipment Booking Requests', 'Live Fleet Tracking Map', 'Route Optimization Tool', 'Delivery Confirmation Log'],
    uniqueInteractions: ['Accepting/rejecting transport requests', 'Updating shipment status in real-time', 'Managing vehicle and driver availability.'],
  },
  [UserRole.BankFinancial]: {
    role: UserRole.BankFinancial,
    title: 'Bank/Financial',
    description: 'Facilitate transactions, loans, and financial services.',
    icon: BankFinancialIcon,
    coreObjective: 'To provide financial products and services tailored to the agricultural sector.',
    dashboardElements: ['Loan Application Queue', 'Transaction Monitoring', 'Client Financial Health Reports', 'Agri-Finance News'],
    uniqueInteractions: ['Assessing credit risk for agricultural loans', 'Facilitating secure escrow transactions between buyers and sellers.'],
  },
  [UserRole.DataAnalyst]: {
    role: UserRole.DataAnalyst,
    title: 'Data Administrator',
    description: 'Manage and analyze aggregated platform data for insights.',
    icon: DataAnalystIcon,
    coreObjective: 'To analyze platform data to generate insights, create reports, and monitor system health.',
    dashboardElements: ['Data Visualization Suite', 'Custom Report Builder', 'Data Export/Import Tools', 'System Performance Metrics'],
    uniqueInteractions: ['Querying the aggregated platform database', 'Building predictive models for market trends', 'Ensuring data integrity and security.'],
  },
};
